language: node_js
node_js:
  - "6"
cache:
  directories:
  - node_modules
env:
- TRAVIS_NODE_VERSION="6.3"
services:
- "postgresql"
install:
- npm install
before_script:
  - psql -c 'create database "todos-test";' -U postgres
  - sequelize db:migrate
script:
- npm test
- "./node_modules/.bin/grunt collect_static"
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIWXCESNME453J7IA
  secret_access_key:
    secure: TAnknlPBWdpHn1BcnNhHy8bN+wpf+yJJahtItK4D6e6/LKltx3s1U5yAduD8PcvT2U0K3nx8/mAdGVrZ0oSZN7e0m31d7p/z4OFJgFZQlcIKsgyeV98/UaV32wWOIEpAobZmgu+PGU5psoDHqnfJhCEsyp4MtJ/xEXHzIyPm0ITNtqB5DsIH+XEHR/wwJUhLGhuUNERXJlzdPnjy2qnVWxwIJu2UWlZ/EzLJaNh9H30PHLYTTP5FdcJDTIUSjnr5fN4VYmvQQg6LTt37KJyglo/2/XW2BSkghCNDhGFydHip2FOMa6OjY9kPPF0KkP90DmEjfukPvr7PKAXJFTz21pYYGhe/F4iCaVTVtR9B7mj0gmfFfKzaB08Ivxz2qOPe8jcVUVFCKqf+TucrCuicsII0xg+oMc74ModmpmQ45c2R2ERIktREpzMRM8P76awoMYvB3G25Ic9z8eu7fIK/+qJpb3+pI7tVvYQHTWdNGpoFfxMEDbJPP7aCgyGTE0R8MsdPUM8ykzPwSwCnZB0RpiRezCce951h4YfNtlgzRLzvRdWuVPgacrHKlib2+uukZWr1g8hSwI5HXx5LZXkrAH+SSdjVJcHiMClibbhpH4gQ1DLWynrT+Yj00bcUjIfoyJFVaviFAQcxjsieX8JDYIuo0w9zuwMMQkBKbq9C2BY=
  region: us-west-2
  app: todomvc-2
  env: todomvc-2-dev
  bucket_name: elasticbeanstalk-us-west-2-204160565325
  on:
    repo: AndrewSouthpaw/todomvc-plusplus
